const actions = {
  SET_STATE: 'appointments/SET_STATE',
  GET_APPOINTMENT_LIST: 'appointments/GET_APPOINTMENT_LIST',
  APPEND_APPOINTMENT_LIST: 'appointments/APPEND_APPOINTMENT_LIST',
  UPDATE_APPOINTMENT_LIST: 'appointments/UPDATE_APPOINTMENT_LIST',
  GET_APPOINTMENT_THERAPIST: 'appointments/GET_APPOINTMENT_THERAPIST',
  GET_APPOINTMENT_LEARNER: 'appointments/GET_APPOINTMENT_LEARNER',
  GET_APPOINTMENT: 'appointments/GET_APPOINTMENT',
  UPDATE_APPOINTMENT: 'appointments/UPDATE_APPOINTMENT',
}

export default actions
